# -*- coding: utf-8 -*-
"""codigoBase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QMA5Nqy0de6P9VAztVYW998gWBe0EFq0
"""

import pandas as pd
import plotly.express as px
import streamlit as st

#Lendo o dataset
df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')

#Melhorando o nome das colunas da tabela
df = df.rename(columns={'newDeaths': 'Novos óbitos','newCases': 'Novos casos','deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes','totalCases_per_100k_inhabitants':'Casos por 100 mil habitantes'})

#Seleção do Estado
estados = list(df['state'].unique())
state = st.sidebar.selectbox('Qual o estado?', estados)

#Seleção da Coluna
colunas = ['Novos óbitos','Novos casos','Óbitos por 100 mil habitantes','Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Qual o tipo de informação?', colunas)

#Seleção das linhas que pertence ao Estado
df = df[df['state'] == state]

fig = px.line(df, x="date", y=column, title=column + ' - ' + state)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})

st.title('Dados da Covid - Brasil')
st.write('Nessa aplicação, o usuário tem a opção de escolher o estado e o tipo de informações para mostrar o grático.')

st.plotly_chart(fig, use_container_width=True)

st.caption('Dados obtidos a partir do site: https://github.com/wcota/covid19br')